import type { Metadata } from "next";

import { inter } from "./_lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Vesugusto",
    default: "Vesugusto",
  },
  description:
    "Dashbord web app for the Vesugusto website, generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
