import type { Metadata } from "next";

import { inter } from "./_lib/fonts";
import "./globals.css";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: {
    template: "%s | Vesugusto",
    default: "Vesugusto",
  },
  description:
    "Dashbord web app for the Vesugusto website, generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${inter.className} bg-style mx-auto h-full max-w-[95rem] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
